# Generates the EmbeddedExporter.cpp table (see LibreDiffusion/EmbeddedExporter.hpp).
#
#   cmake -DLIST=<manifest> -DOUT=<cpp> -P EmbedFiles.cmake
#
# The manifest has one entry per line: <relative path>|<absolute path>|<0|1 executable>.
# Bytes are written as \xHH string literals, one literal per MiB: every byte is an escape, so no
# escape can swallow the character after it, and compilers parse string literals orders of
# magnitude faster than brace-initialised byte arrays.

if(NOT DEFINED LIST OR NOT DEFINED OUT)
  message(FATAL_ERROR "EmbedFiles.cmake: LIST and OUT are required")
endif()

set(chunk 1048576)
set(id_source "")
set(table "")
set(index 0)

file(WRITE "${OUT}" "// Generated by cmake/EmbedFiles.cmake -- do not edit.\n#include \"EmbeddedExporter.hpp\"\n\nnamespace\n{\n")

if(EXISTS "${LIST}")
  file(STRINGS "${LIST}" entries)
endif()
foreach(entry IN LISTS entries)
  string(REPLACE "|" ";" fields "${entry}")
  list(GET fields 0 rel)
  list(GET fields 1 abs)
  list(GET fields 2 exec)

  file(SHA256 "${abs}" digest)
  string(APPEND id_source "${rel}:${digest};")

  file(SIZE "${abs}" total)
  file(APPEND "${OUT}" "const char f${index}[] =\n")
  if(total EQUAL 0)
    file(APPEND "${OUT}" "\"\"\n")
  endif()
  set(off 0)
  while(off LESS total)
    file(READ "${abs}" hex OFFSET ${off} LIMIT ${chunk} HEX)
    string(REGEX REPLACE "(..)" [[\\x\1]] escaped "${hex}")
    file(APPEND "${OUT}" "\"${escaped}\"\n")
    math(EXPR off "${off} + ${chunk}")
  endwhile()
  file(APPEND "${OUT}" ";\n")

  if(exec)
    set(exec_literal "true")
  else()
    set(exec_literal "false")
  endif()
  string(APPEND table "    {\"${rel}\", {f${index}, sizeof(f${index}) - 1}, ${exec_literal}},\n")
  math(EXPR index "${index} + 1")
endforeach()

if(index GREATER 0)
  string(SHA256 id "${id_source}")
  string(SUBSTRING "${id}" 0 16 id)
  file(APPEND "${OUT}" "const lo::EmbeddedFile files[] = {\n${table}};\n")
  set(files_span "files")
else()
  set(id "")
  set(files_span "")
endif()

file(APPEND "${OUT}" "}\n\nnamespace lo\n{\nstd::span<const EmbeddedFile> embedded_exporter_files() noexcept\n{\n  return {${files_span}};\n}\n\nstd::string_view embedded_exporter_id() noexcept\n{\n  return \"${id}\";\n}\n}\n")
